LabaManageSys.WebUI/Controllers/JournalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LabaManageSys.WebUI.Abstract;
using LabaManageSys.WebUI.Models;
using LabaManageSys.WebUI.ViewModels.Journal;
using LabaManageSys.WebUI.ViewModels.TeachPlan;

namespace LabaManageSys.WebUI.Controllers
{
    [Authorize(Roles = "Teachers")]
    public class JournalController : Controller
    {
        private ILessonsRepository lessonRepository;
        private IUsersRepository userRepository;
        private int pageSize = 10;

        public JournalController(ILessonsRepository repoL, IUsersRepository repoU)
        {
            this.lessonRepository = repoL;
            this.userRepository = repoU;
        }

        // GET: Journal
        public ActionResult List()
        {
            ListViewModel model = new ListViewModel { Courses = this.lessonRepository.Courses };
            return this.View(model);
        }

        public ActionResult Edit(int courseId, int page = 1)
        {
            JournalEditModel model = new JournalEditModel
                {
                    Course = this.lessonRepository.GetCourseById(courseId),
                    Lessons = this.lessonRepository.GetLessonsByCourse(courseId, page, this.pageSize),
                    Users = this.userRepository.GetUsersInRole("Students"),
                    PagingInfo = 
                    new PagingInfo
                    {
                        CurrentPage = page,
                        TotalItems = this.lessonRepository.LessonsCountByCourse(courseId),
                        ItemsPerPage = this.pageSize
                    }
            };
            return this.View(model);
        }

        [HttpPost]
        public void AddUserMissLesson()
        {
            var userId = Request.Form.GetValues("userId")[0];
            var lessonId = Request.Form.GetValues("lessonId")[0];
            var userLesson = new UserLesson(lessonId, userId);
            this.lessonRepository.AddUserMissLesson(userLesson);
        }

        [HttpPost]
        public void RemoveUserMissLesson()
        {
            var userId = Request.Form.GetValues("userId")[0];
            var lessonId = Request.Form.GetValues("lessonId")[0];
            var userLesson = new UserLesson(lessonId, userId);
            this.lessonRepository.RemoveUserMissLesson(userLesson);
        }

        [HttpPost]
        public ActionResult Edit(JournalEditModel journal)
        {
            if (ModelState.IsValid)
            {
                // this.lessonRepository.UpdateUsersMissLessons(journal.UsersMissLesson, journal.Course.CourseId);
                this.TempData["message"] = string.Format("Изменения в журнале посещений по \"{0}\" были сохранены", journal.Course.Name);
                return this.RedirectToAction("List");
            }
            else
            {
                // Что-то не так со значениями данных
                return this.View(journal);
            }
        }
    }
}

LabaManageSys.WebUI/Controllers/RoleController.cs
using System.Linq;
using System.Web.Mvc;
using LabaManageSys.WebUI.Abstract;
using LabaManageSys.WebUI.Filters;
using LabaManageSys.WebUI.Models;
using LabaManageSys.WebUI.ViewModels.Role;

namespace LabaManageSys.WebUI.Controllers
{
    [Authorize(Roles = "Administrators")]
    public class RoleController : Controller
    {
        private IUsersRepository repository;

        public RoleController(IUsersRepository repo)
        {
            this.repository = repo;
        }

        public ViewResult List()
        {
            ListViewModel roles = new ListViewModel { Roles = this.repository.RoleModels };
            return this.View(roles);
        }

        public ViewResult Edit(int roleId)
        {
            EditViewModel viewRole = new EditViewModel { Role = this.repository.GetRoleById(roleId) };
            return this.View(viewRole);
        }

        // Перегруженная версия Edit() для сохранения изменений
        [HttpPost]
        public ActionResult Edit(RoleModel role)
        {
            if (ModelState.IsValid)
            {
                this.repository.RoleUpdate(role);
                this.TempData["message"] = string.Format("Изменения в роли \"{0}\" были сохранены", role.Name);
                return this.RedirectToAction("List");
            }
            else
            {
                // Что-то не так со значениями данных
                return this.View(role);
            }
        }

        // Создание роли
        public ViewResult Create()
        {
            return this.View("Edit", new EditViewModel { Role = new RoleModel() });
        }

        // Удаление роли из базы
        [HttpPost]
        public ActionResult Delete(int roleId)
        {
            if (!this.repository.AreUsersInRole(roleId))
            {
                RoleModel deletedRole = this.repository.RoleDelete(roleId);
                if (deletedRole != null)
                {
                    this.TempData["message"] = string.Format("Роль \"{0}\" успешно удалена.", deletedRole.Name);
                }
            }
            else
            {
                this.TempData["message"] = string.Format("Роль \"{0}\" нельзя удалить пока есть пользователи в этой роли.", this.repository.GetRoleById(roleId).Name);
            }

            return this.RedirectToAction("List");
        }
    }
}

LabaManageSys.WebUI/Controllers/TaskLoadController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LabaManageSys.WebUI.Abstract;
using LabaManageSys.WebUI.Models;
using LabaManageSys.XML.Abstract;
using LabaManageSys.XML.Models;

namespace LabaManageSys.WebUI.Controllers
{
    [Authorize(Roles = "Teachers")]
    public class TaskLoadController : Controller
    {
        private IxmlProcessor processor;
        private ITasksRepository repository;

        public TaskLoadController(IxmlProcessor proc, ITasksRepository repo)
        {
            this.processor = proc;
            this.repository = repo;
        }

        // GET: TaskLoad
        public ActionResult Index()
        {
            return this.View();
        }

        public ActionResult Downloadfile()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory + "uploads/";
            string fileName = "tasks.xml";

            var tasks = this.repository.Tasks.Select(_ => 
            new TaskXMLModel
            {
                TaskId = _.TaskId,
                Author = _.Author,
                Level = _.Level,
                Topic = _.Topic,
                Text = _.Text
            }).ToList();
            this.processor.DownloadTasksToFile(tasks, path + fileName);
            this.TempData["message"] = string.Format("Отправка файла началась.");
            return this.File(path + fileName, "text/xml", fileName);
        }

        [HttpPost]
        public ActionResult Uploadfile(HttpPostedFileBase xmlfile = null)
        {
            if (xmlfile != null && xmlfile.ContentLength > 0 && xmlfile.ContentType == "text/xml")
            {
                var tasks = this.processor.UploadTasksFromFile(xmlfile.InputStream);
                this.repository.TaskAddAll(tasks.Select(_ => 
                new TaskModel
                {
                    TaskId = _.TaskId,
                    Author = _.Author,
                    Level = _.Level,
                    Topic = _.Topic,
                    Text = _.Text
                }).ToList());
            }
            
            return this.RedirectToAction("List", "TaskManage");
        }
    }
}

LabaManageSys.WebUI/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using LabaManageSys.WebUI.Abstract;
using LabaManageSys.WebUI.Filters;
using LabaManageSys.WebUI.Models;
using LabaManageSys.WebUI.ViewModels.User;

namespace LabaManageSys.WebUI.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private IUsersRepository repository;
        private ILogger log;
        private int pageSize = 5;//магические числа нужно заменять на константы

        public UserController(IUsersRepository repo, ILogger log)
        {
            this.log = log;
            this.repository = repo;
        }

        public ViewResult List(int page = 1)
        {
            ListViewModel model = new ListViewModel
            {
                Users = this.repository.GetUserList(page, this.pageSize),
                PagingInfo = new PagingInfo { CurrentPage = page, TotalItems = this.repository.UserModels.Count(), ItemsPerPage = this.pageSize }
            };
            return this.View(model);
        }

        [Authorize(Roles = "Administrators")]
        public ViewResult Edit(int userId)
        {
            EditViewModel model = new EditViewModel
            {
                User = this.repository.GetUserById(userId),
                Roles = this.repository.RoleModels
            };
            return this.View(model);
        }

        // Перегруженная версия Edit() для сохранения изменений
        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public ActionResult Edit(UserModel user)
        {
            if (ModelState.IsValid)
            {
                var message = "User " + user.Name + ((user.UserId == 0) ? " created" : " edited");
                this.repository.UserUpdate(user);
                this.TempData["message"] = $"Изменения в пользователе {user.Name} были сохранены";
                this.log.Info(message);
                return this.RedirectToAction("List");
            }
            else
            {
                // Что-то не так со значениями данных. (коммент лишний, из кода и так все понятно)
                return this.View(new EditViewModel
                {
                    User = user,
                    Roles = this.repository.RoleModels
                });
            }
        }

        // Создание пользователя
        [Authorize(Roles = "Administrators")]
        public ViewResult Create()
        {
            var model = new EditViewModel
            {
                User = new UserModel { RoleId = this.repository.GetFirstRole().RoleId },
                Roles = this.repository.RoleModels
            };

            return this.View("Edit", model);
        }

        // Удаление пользователя из базы
        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public ActionResult Delete(int userId)
        {
            UserModel deletedUser = this.repository.UserDelete(userId);
            if (deletedUser != null)
            {
                this.TempData["message"] = string.Format("Пользователь \"{0}\" успешно удален.", deletedUser.Name);
            }

            return this.RedirectToAction("List");
        }
    }
}

LabaManageSys.WebUI/Views/Shared/ErrorPage.cshtml
@model HandleErrorInfo
@{
    //Layout = null;
    ViewBag.Title = "Извините, возникли проблемы!";
}

<h2>Извините</h2>
<span>
    <b>Возникло непредвиденное событие. Обратитесь пожалуйста к администратору сайта.</b>
</span>
<div>
    @Html.ActionLink("Вернуться обратно", "Index", "Home")
</div>

LabaManageSys.WebUI/Views/Shared/TaskSummary.cshtml
@model LabaManageSys.WebUI.Models.TaskModel

<div class="well">
    <h2>@Model.Topic</h2>
    <h3>уровень: @Model.Level автор: @Model.Author</h3>
    <h3>@Model.Text</h3>    
</div>

LabaManageSys.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</div>

LabaManageSys.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/datepicker.min.css" rel="stylesheet" type="text/css">
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LabaManageSystem", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-left">
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Пользователи", "List", "User", new { area = "" }, new { @class = "btn" })
                }
                @if (User.IsInRole("Administrators"))
                {
                    @Html.ActionLink("Роли", "List", "Role", new { area = "" }, new { @class = "btn" })
                }
                @if (User.IsInRole("Teachers"))
                {
                    @Html.ActionLink("Учебный план", "List", "TeachPlan", new { area = "" }, new { @class = "btn" })
                    @Html.ActionLink("Журнал посещаемости", "List", "Journal", new { area = "" }, new { @class = "btn" })
                    @Html.ActionLink("Загрузка заданий", "Index", "TaskLoad", new { area = "" }, new { @class = "btn" })
                    @Html.ActionLink("Скачать задания", "DownloadFile", "TaskLoad", new { area = "" }, new { @class = "btn" })
                }
            </div>
            <div class="navbar-right">
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink(User.Identity.Name,"")
                    @Html.ActionLink("Выход", "Logoff", "Account", new { area = "" }, new { @class = "btn" })
                }
                else
                {
                    @Html.ActionLink("Логин", "Login", "Account", new { area = "" }, new { @class = "btn" })
                    @Html.ActionLink("Регистрация", "Register", "Account", new { area = "" }, new { @class = "btn" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div>
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/datepicker.min.js"></script>
    @RenderSection("scripts", false)
    <script type="text/javascript">
        $('#Dates').datepicker({
            // Можно выбрать тольо даты, идущие за сегодняшним днем, включая сегодня
            inline: true,
            timepicker: true,
            startHour: 9,
            minHours: 9,
            maxHours: 18,
            minDate: new Date()
        })
         // Сделаем неактивными воскресенье и субботу
        var disabledDays = [0, 6];

        $('#Dates').datepicker({
            onRenderCell: function (date, cellType) {
                if (cellType == 'day') {
                    var day = date.getDay(),
                        isDisabled = disabledDays.indexOf(day) != -1;

                    return {
                        disabled: isDisabled
                    }
                }
            }
        })

    </script>

</body>
</html>