LabaManageSys.WebUI/ViewModels/Role/EditViewModel.cs
using LabaManageSys.WebUI.Models;

namespace LabaManageSys.WebUI.ViewModels.Role
{
    public class EditViewModel
    {
        public RoleModel Role { get; set; }
    }
}

LabaManageSys.WebUI/ViewModels/Role/ListViewModel.cs
using System.Collections.Generic;
using LabaManageSys.WebUI.Models;

namespace LabaManageSys.WebUI.ViewModels.Role
{
    public class ListViewModel
    {
        public IEnumerable<RoleModel> Roles { get; set; }
    }
}

LabaManageSys.WebUI/ViewModels/Task/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using LabaManageSys.WebUI.Models;

namespace LabaManageSys.WebUI.ViewModels.Task
{
    public class EditViewModel
    {
        public TaskModel Task { get; set; }
    }
}

LabaManageSys.WebUI/ViewModels/Task/ListViewModel.cs
using System.Collections.Generic;
using System.Linq;
using LabaManageSys.WebUI.Models;

namespace LabaManageSys.WebUI.ViewModels.Task
{
    public class ListViewModel
    {
        public IEnumerable<TaskModel> Tasks { get; set; }

        public FilterLists Lists { get; set; }

        public FilterModel Filter { get; set; }

        public PagingInfo PagingInfo { get; set; }

        public void SetTotalItems()
        {
            this.PagingInfo.TotalItems = this.Tasks.Count();
        }
    }
}

LabaManageSys.WebUI/ViewModels/TeachPlan/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using LabaManageSys.WebUI.Models;

namespace LabaManageSys.WebUI.ViewModels.TeachPlan
{
    public class EditViewModel
    {
        public CourseModel Course { get; set; }

        public string Dates { get; set; }

        public IEnumerable<DateTime> GetArrayDates()
        {
            var str_dates = this.Dates.Replace(".", "/").Trim().Split(',');
            foreach (var str in str_dates)
            {
                yield return DateTime.ParseExact(str, "g", new CultureInfo("fr-FR"));
            }
        }
    }
}

LabaManageSys.WebUI/ViewModels/TeachPlan/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using LabaManageSys.WebUI.Models;

namespace LabaManageSys.WebUI.ViewModels.TeachPlan
{
    public class ListViewModel
    {
        public IEnumerable<CourseModel> Courses { get; set; }
    }
}

LabaManageSys.WebUI/ViewModels/User/EditViewModel.cs
using System.Collections.Generic;
using LabaManageSys.WebUI.Models;

namespace LabaManageSys.WebUI.ViewModels.User
{
    public class EditViewModel
    {
        public UserModel User { get; set; }

        public IEnumerable<RoleModel> Roles { get; set; }
    }
}

LabaManageSys.WebUI/ViewModels/User/ListViewModel.cs
using System.Collections.Generic;
using LabaManageSys.WebUI.Models;

namespace LabaManageSys.WebUI.ViewModels.User
{
    public class ListViewModel
    {
        public IEnumerable<UserModel> Users { get; set; }

        public PagingInfo PagingInfo { get; set; }
    }
}

LabaManageSys.WebUI/Controllers/TeachPlanController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LabaManageSys.WebUI.Abstract;
using LabaManageSys.WebUI.Models;
using LabaManageSys.WebUI.ViewModels.TeachPlan;

namespace LabaManageSys.WebUI.Controllers
{
    [Authorize(Roles = "Teachers")]
    public class TeachPlanController : Controller
    {
        private ILessonsRepository repository;
        
        public TeachPlanController(ILessonsRepository repo)
        {
            this.repository = repo;
        }

        // GET: Teacher
        public ActionResult List()
        {
            ListViewModel model = new ListViewModel { Courses = this.repository.Courses };
            return this.View(model);
        }

        public ActionResult Edit(int courseId)
        {
            EditViewModel course = new EditViewModel
            {
                Course = this.repository.GetCourseById(courseId),
                Dates = string.Join(",", this.repository.GetDatesByCourse(courseId).Select(x => x.ToString()).ToArray())
            };
            return this.View(course);
        }

        [HttpPost]
        public ActionResult Edit(EditViewModel courseModel)
        {
            CultureInfo provider = CultureInfo.InvariantCulture;
            if (ModelState.IsValid)
            {
                this.repository.CourseUpdate(courseModel.Course, courseModel.GetArrayDates());
                this.TempData["message"] = string.Format("Изменения в курсе \"{0}\" были сохранены", courseModel.Course.Name);
                return this.RedirectToAction("List");
            }
            else
            {
                // Что-то не так со значениями данных
                return this.View(new EditViewModel
                {
                    Course = courseModel.Course
                });
            }
        }

        // Создание курса
        public ViewResult Create()
        {
            return this.View("Edit", new EditViewModel { Course = new CourseModel() });
        }

        // Удаление курса из базы
        [HttpPost]
        public ActionResult Delete(int courseId)
        {
           CourseModel deletedCourse = this.repository.CourseDelete(courseId);
           if (deletedCourse != null)
              {
                this.TempData["message"] = string.Format("Курс \"{0}\" успешно удален.", deletedCourse.Name);
              }

            return this.RedirectToAction("List");
        }
    }
}

LabaManageSys.WebUI/Views/TeachPlan/Edit.cshtml
@model LabaManageSys.WebUI.ViewModels.TeachPlan.EditViewModel
@{
    ViewBag.Title = "Редактируем курс";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        @if (Model.Course.Name != null && Model.Course.Name != "")
        {
            <h3> Редактируем курс - "@Model.Course.Name"</h3>
            <p> Занятия - @Model.Dates </p>
        }
        else
        {
            <h3> Добавляем новый курс</h3>
        }
    </div>

    @using (Html.BeginForm("Edit", "TeachPlan"))
    {
        @Html.AntiForgeryToken();
    <div class="panel-body">
        <div> <p>@Html.HiddenFor(_ => _.Course.CourseId)</p> </div>
        <div class="form-group">
            <p>@Html.LabelFor(_ => _.Course.Name)</p>
            <div>
                <p>@Html.EditorFor(_ => _.Course.Name)</p>
            </div>
        </div>
        <div>
                <input size="600" style="max-width: 600px" id="Dates" type="text" name="Dates" class="datepicker-here"
                   data-multiple-dates="20"
                   data-multiple-dates-separator=","
                   data-timepicker="true"
                   data-position='right top' 
                   data-dates="@Model.Dates"    />
       </div>
    </div>
    <div class="panel-footer">
        <input type="submit" value="Сохранить" class="btn btn-primary" />
        @Html.ActionLink("Отменить изменения и вернуться к списку", "List", null, new
        {
           @class = "btn btn-default"
        })
    </div>
    }
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            var myDatepicker = $('#Dates').datepicker().data('datepicker');
            var str = $('#Dates').attr('data-dates');
            if (str != "" && str != null) {
                var dates = str.split(',');
                var date = [];
                for (var i = 0; i < dates.length; i++) {
                    date[i] = (new Date(dates[i]));
                }
                myDatepicker.selectDate(date);
            }
        });
    </script>
}

LabaManageSys.WebUI/Views/TeachPlan/List.cshtml
@model LabaManageSys.WebUI.ViewModels.TeachPlan.ListViewModel
@{
    ViewBag.Title = "Список курсов";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Список учебных курсов</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th>Имя</th>
                <th class="text-center">Действия</th>
            </tr>
            @foreach (var item in Model.Courses)
            {
                <tr>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.CourseId })</td>
                    <td class="text-center">
                        <button class="btn btn-danger btn-xs" data-toggle="modal" data-target="#@item.CourseId">Удалить</button>
                        <!-- Modal -->
                        <div class="modal fade" id=@item.CourseId role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <p style="font-size: large">
                                            Удалить курс @item.Name ?
                                        </p>
                                    </div>
                                    <div class="modal-footer">
                                        @using (Html.BeginForm("Delete", "TeachPlan"))
                                        {
                                            @Html.Hidden("CourseId", item.CourseId)
                                            <input type="submit"
                                                   class="btn btn-danger"
                                                   value="Удалить" />
                                                <button class="btn btn-default" data-dismiss="modal">Отменить</button>
                                        }
                                    </div>

                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Добавить курс", "Create", null,
            new { @class = "btn btn-default" })
    </div>
</div>